#' Line plot for one-at-a-time sensitivity analysis
#'
#' @param X_oaat Matrix of one-at-time input design generated by oaat_design in package emtools
#' @param y_oaat_mean vector of one-at-a-time output
#' @param y_oaat_sd standard deviation vector of one-at-a-time output.
#' @param n_oaat Number of samples for each input
#' @param nr Number of rows in the plot
#' @param nc Number of colums in the plot
#' @param linecol line colour
#' @param shadecol uncertainty shade colour
#' @param ... Further plotting parameters (input to plot)
#'
#' @return A plot of the impact of turning each parameter from low to high in isolation.
#' @export
#'
#' @examples
oaatLinePlot <- function(X_oaat, y_oaat_mean, y_oaat_sd,
                         n_oaat, nr, nc, linecol = 'black', shadecol = 'grey', ...){
  
  
  col.transp <- adjustcolor(shadecol, alpha = 0.5)
  par(mfrow = c(6,6), oma = c(0.1,0.1,3,0.1), mar = c(2,2,3,1))
  
  for(i in 1:ncol(X_oaat)){
    
    ix <- seq(from = ((i*n_oaat) - (n_oaat-1)), to =  (i*n_oaat), by = 1)
    
    plot(X_oaat[ix,i], y_oaat_mean[ix], 
         xlim = c(0,1), ylim = range(c(y_oaat_mean+(2*y_oaat_sd), y_oaat_mean-(2*y_oaat_sd))) ,
         xlab = colnames(X_oaat)[i],
         type= 'n',
         bty = 'n', ...)
    
    polygon(x = c(X_oaat[ix, i], rev(X_oaat[ix, i])),
            y = c(y_oaat_mean[ix] - (2*y_oaat$sd[ix]), rev(y_oaat_mean[ix] + (2*y_oaat_sd[ix]))),
            col = col.transp, border = col.transp)
    
    lines(X_oaat[ix,i], y_oaat_mean[ix], xlim = c(0,1), lty = 'solid', col = linecol)
    mtext(colnames(X_oaat)[i], side = 3, line = 0.5)
    
  }
  
  mtext('One-at-a-time sensitivity', side = 3, outer = TRUE, cex = 1.5)
  
}